'use client'
import React, { useRef } from 'react'
import Image from 'next/image'
import { ChevronLeft, ChevronRight } from 'lucide-react'
import {
  motion,
  useScroll,
  useSpring,
  useTransform,
  useVelocity,
  useAnimationFrame,
  useMotionValue,
} from "motion/react"
import { wrap } from "motion"

interface ParallaxProps {
  children: string
  baseVelocity: number
  className?: string
}

function ParallaxText({ children, baseVelocity = 100, className = "" }: ParallaxProps) {
  const baseX = useMotionValue(0)
  const { scrollY } = useScroll()
  const scrollVelocity = useVelocity(scrollY)
  const smoothVelocity = useSpring(scrollVelocity, {
    damping: 50,
    stiffness: 400,
  })
  const velocityFactor = useTransform(smoothVelocity, [0, 1000], [0, 5], {
    clamp: false,
  })

  /**
   * This is a magic wrapping for the length of the text - you
   * can replace this with a more dynamic value of course, but it's
   * enough for this example.
   */
  const x = useTransform(baseX, (v) => `${wrap(-20, -45, v)}%`)

  const directionFactor = useRef<number>(1)
  useAnimationFrame((t, delta) => {
    let moveBy = directionFactor.current * baseVelocity * (delta / 1000)

    /**
     * This is what makes it move according to scroll speed
     * and direction.
     */
    if (velocityFactor.get() < 0) {
      directionFactor.current = -1
    } else if (velocityFactor.get() > 0) {
      directionFactor.current = 1
    }

    moveBy += directionFactor.current * moveBy * velocityFactor.get()

    baseX.set(baseX.get() + moveBy)
  })

  /**
   * The number of times to repeat the child text should be enough to span the viewport
   * width plus the maximum offset generated by baseX.
   */
  return (
    <div className="parallax overflow-hidden whitespace-nowrap flex flex-nowrap w-full">
      <motion.div className={`scroller flex flex-nowrap whitespace-nowrap ${className}`} style={{ x }}>
        <span className="block mr-12">{children} </span>
        <span className="block mr-12">{children} </span>
        <span className="block mr-12">{children} </span>
        <span className="block mr-12">{children} </span>
      </motion.div>
    </div>
  )
}

interface WorkProps {
  collections: {
    name: string;
    description: string;
    image: string;
    link: string;
  }[];
  index: number;
  setIndex: React.Dispatch<React.SetStateAction<number>>;
  setOpenedCollection: React.Dispatch<React.SetStateAction<number | null>>;
}

const Work = ({collections, index, setIndex }: WorkProps) => {
  const { scrollY } = useScroll()
  const scrollVelocity = useVelocity(scrollY)
  const smoothVelocity = useSpring(scrollVelocity, {
    damping: 50,
    stiffness: 400,
  })
  
  // Calculate rotation and skew based on velocity
  const skewY = useTransform(smoothVelocity, [-2000, 2000], [-5, 5])
  const rotateY = useTransform(smoothVelocity, [-2000, 2000], [-10, 10])

  return (
    <section id="work" className='relative z-0 w-screen h-[100vh] overflow-hidden bg-black'>
      <div className="z-10 text-center text-white flex flex-row-reverse items-center h-full">
        <div className='w-1/2 h-3/4 pr-8' style={{ perspective: "1000px" }}>
          <motion.div 
            style={{ skewY, rotateY }}
            className="w-full h-full"
          >
            <Image 
              key={index} 
              src={collections[index].image} 
              alt={collections[index].name} 
              width={1920} 
              height={1080} 
              className='w-full h-full object-cover animate-fade-in' 
            />
          </motion.div>
        </div>
        <div className='w-1/2 flex flex-col items-center h-full relative'>
          <div className='w-full h-full flex flex-col items-center justify-center'>
            <div key={index} className='w-full animate-fade-in flex flex-col items-center justify-center gap-2 overflow-hidden'>
              <ParallaxText baseVelocity={-2} className="text-[6vw] leading-[6vw] font-light tracking-widest opacity-15 uppercase">
                {collections[index].name}
              </ParallaxText>
              <ParallaxText baseVelocity={2} className="text-[6vw] leading-[6vw] font-light tracking-widest opacity-30 uppercase">
                {collections[index].name}
              </ParallaxText>
              <ParallaxText baseVelocity={-2} className="text-[6vw] leading-[6vw] font-light tracking-widest uppercase">
                {collections[index].name}
              </ParallaxText>
              <ParallaxText baseVelocity={2} className="text-[6vw] leading-[6vw] font-light tracking-widest opacity-30 uppercase">
                {collections[index].name}
              </ParallaxText>
              <ParallaxText baseVelocity={-2} className="text-[6vw] leading-[6vw] font-light tracking-widest opacity-15 uppercase">
                {collections[index].name}
              </ParallaxText>
            </div>
            <div className='w-full flex items-center justify-center gap-8 pt-12 z-20'>
              <button 
                className="cursor-pointer hover:scale-110 transition-transform" 
                onClick={() => setIndex((index - 1 + collections.length) % collections.length)}
              >
                <ChevronLeft strokeWidth={1} size={48} />
              </button>
              <button 
                className="cursor-pointer hover:scale-110 transition-transform" 
                onClick={() => setIndex((index + 1) % collections.length)}
              >
                <ChevronRight strokeWidth={1} size={48} />
              </button>
            </div>
            <button className='mt-12 text-base tracking-widest duration-300 hover:opacity-70 hover:underline underline-offset-4 uppercase'>
              view collection
            </button>
          </div>
        </div>
      </div>
    </section>
  )
}

export default Work

